const fs = require('fs');
const b64 = 'IyDwn4+oIEhvdGVsSHViCgo+ICoqQSBNb2Rlcm4gSG90ZWwgTWFuYWdlbWVudCBBcHBsaWNhdGlvbioqCgotLS0KCiMjIPCfp6AgQmFja2VuZCBBcmNoaXRlY3R1cmUKCioqTm9kZS5qcyoqIHwgKipFeHByZXNzLmpzKiogfCAqKlBvc3RncmVTUUwqKgoKLS0tCgojIyDinKggQ29yZSBGZWF0dXJlcwoKLSAqKkhvdGVsIENSVUQqKiAtIENvbXBsZXRlIG1hbmFnZW1lbnQgb2YgaG90ZWwgcmVjb3Jkcy4KLSAqKkltYWdlIFVwbG9hZCoqIC0gU2VhbWxlc3MgaW1hZ2UgcHJvY2Vzc2luZyBhbmQgc3RvcmFnZS4KLSAqKlNlYXJjaCAmIFByaWNlIEZpbHRlcmluZyoqIC0gUG93ZXJmdWwgZHluYW1pYyBxdWVyeWluZy4KLSAqKlBhZ2luYXRpb24qKiAtIE9wdGltaXplZCBkYXRhIGxvYWRpbmcgZm9yIGxhcmdlIGRhdGFzZXRzLgotICoqQXV0aGVudGljYXRpb24qKiAtIFNlY3VyZSByb2xlLWJhc2VkIGFjY2VzcyAoQWRtaW4vVXNlcikuCi0gKipIb3RlbCBEZXRhaWxzICYgTWFwKiogLSBJbnRlcmFjdGl2ZSBsb2NhdGlvbiByZW5kZXJpbmcuCgotLS0K';
const content = Buffer.from(b64, 'base64').toString('utf8');
fs.writeFileSync('C:/Users/HP/OneDrive/Desktop/hotel-management/hotel-backend/README.md', content);
console.log('README created successfully!');
